import Menu from '@/components/menu/Menu';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body>
				<main>
					<Menu />
					{children}
				</main>{' '}
			</body>
		</html>
	);
}
